---
title: "Creating R Projects"
output: html_notebook
---

Steps to create R projects:
1.	Navigate to directory that will host the project folder.
2.	In R, load ‘rrtools’ and ‘workflowr’
3.	Run ‘rrtools’ code to create research compendium:
a.	rrtools::use_compendium("myproject ")
b.	usethis::use_mit_license(name = "Jonathan J Maynard")
c.	usethis::use_git()
d.	Create github ‘repo’ token for “myproject”
e.	usethis::use_github(auth_token = "xxxx", protocol = "https", private = FALSE)
f.	rrtools::use_readme_rmd()
g.	rrtools::use_analysis()
h.	rename the ‘analysis’ folder to ‘research’
i.	rrtools::use_dockerfile()
j.	rrtools::use_travis()
4.	Run ‘workflowr’ code to create research website
a.	wflow_start("myproject_site")
b.	wflow_build() and wflow_view() to build and view website
c.	wflow_publish(c("analysis/index.Rmd", "analysis/about.Rmd", "analysis/license.Rmd"), "Publish the initial files for myproject")
d.	wflow_status() to check if docs have been published
5.	Integreate rrtools folder and workflow folder:
a.	Move items from "myproject_site" to "myproject "
6.	Commit changes with Git and push to GitHub. All future changes can be pushed to


```{r}
library(rrtools)
library(workflowr)

rrtools::use_compendium("ESG.Mapping")
usethis::use_mit_license(name = "Jonathan J Maynard")
usethis::use_git()
#Create github ‘repo’ token for “myproject”
usethis::use_github(auth_token = "444c113daec7d9bc845e6959845c6a4c7a1dc30d", protocol = "https", private = FALSE)
rrtools::use_readme_rmd()
rrtools::use_analysis()
#rename the ‘analysis’ folder to ‘manuscript’
rrtools::use_dockerfile()
rrtools::use_travis()

#Run ‘workflowr’ code to create research website
wflow_start("ESG.Mapping_site", git = FALSE)
wflow_build() #to build  website
wflow_view()  #view website
wflow_publish(c("analysis/index.Rmd", "analysis/about.Rmd", "analysis/license.Rmd"), "Publish the initial files for myproject")
wflow_status() #to check if docs have been published

#Integreate rrtools folder and workflow folder: 
  #erase workflowr README.Rmd
  #erase rrtools .gitignore
  #move manuscript/data files to data/
  #erase empty manuscript/data folder
  #erase R/ folder
  #move README.md in /output folder to data/derived/ and erase /output

#Move items from "ESG.Mapping_site" to "ESG.Mapping". Erase "ESG.Mapping_site" folder
#Commit changes with Git and push to GitHub. All future changes can be pushed to


```

